#!/bin/sh
#
# radish-radio:		Starts the Radish SignFetcher daemon
# $id:$

DAEMON_PATH=/usr/local/radish/bin/sign_fetcher.rb
DAEMON_NAME=Radish::SignFetcher
DAEMON_LOG=/export/hda3/tmp/radishcache/SignFetcher.log
# Sanity checks.
[ -x $DAEMON_PATH ] || exit 1



RETVAL=0
case "$1" in
  start)
    echo -n "Starting Radish Sign Fetcher"
    start-stop-daemon -c radish:dialout -g dialout -u radish --start --exec $DAEMON_PATH --quiet >/dev/null
    RETVAL=$?
    echo "."
  ;;
  stop)
    echo -n "Stopping Radish Sign Fetcher"
    pkill -f $DAEMON_NAME
    RETVAL=$?
    echo "."
  ;;
  force-reload)
    $0 stop
    $0 start
  ;;
  restart)
    $0 force-reload
  ;;
  status)
    echo -n "Status of $(basename $0) service: "
    if pgrep -f $DAEMON_NAME > /dev/null ; then
      if find $DAEMON_LOG -mmin -8 | grep -q .; then
        echo "running."
        RETVAL=0
      else
        echo "borked."
        RETVAL=2
      fi
    else
      echo "not running."
      RETVAL=3
    fi
  ;;
  *)
    echo "Usage: /etc/init.d/$(basename $0) {start|stop|force-reload|restart|status}"
    RETVAL=1
  ;;
esac
exit $RETVAL
